POST https://node-api-treino.onrender.com/videos
Content-Type: application/json

{
    "title": "Video node",
    "description": "Video Node description",
    "duration": 3600
}

###

GET https://node-api-treino.onrender.com/videos

###
PUT https://node-api-treino.onrender.com/videos/0379c5a6-80bf-4bc4-be99-fd6df4391a08
Content-Type: application/json

{
    "title": "Video 2",
    "description": "Video 2 description",
    "duration": 3600
}

###
DELETE https://node-api-treino.onrender.com/videos/7d2f7245-b138-4c0f-bc98-32df74984cb6
